### ISSUE TITLE
Библиотекой не парсится?

### ISSUE THREAD

**Issue by coursar** [flashxxx2/cinemahub#1]
https://github.com/flashxxx2/cinemahub/blob/e893e11ea937b7c13725be3c99ab7d86e96950e4/src/main/java/tech/itpark/cinemahub/service/impl/MediaServiceImpl.java#L67-L91

**Comment by flashxxx2** [comment]
Честно говоря, я не смог найти достойного примера применения этой библиотеки и пошел по этому пути.

**Comment by coursar** [comment]
Какой? Надо было посмотреть в сторону Apache Commons или другого CSV Reader'а

**Comment by flashxxx2** [comment]
openCsv пытался
